pg_host: "localhost"
pg_port: "5432"
pg_username: "postgres"
pg_password: "your_password"
pg_dbname: "postgres"
supabase_url: "https://your-project-url.supabase.co"
supabase_api_key: "your_api_key"
supabase_ws_url: "wss://[project-ref].supabase.co/realtime/v1/websocket?apikey=[anon-token]&log_level=info&vsn=1.0.0"
supabase_password: "your_project_password"
redis_host: "localhost"
redis_port: "6379"
redis_password: ""
app_port: ":3000"
api_key: "your-secret-key"
